"use client"

import { useState, useTransition } from "react"
import { useRouter } from "next/navigation"
import Link from "next/link"
import { registerAction, type RegisterPayload } from "@/app/actions/auth"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { AlertCircle, ArrowLeft, ArrowRight, Check, Info, Plus, Trash2 } from "lucide-react"

type Family = { name:string; status:string; occupation:string; incomePerMonth:string; address:string; phone:string; medicalHistory:string }
type Cost = { label:string; amount:string }
const emptyFamily = ():Family => ({name:"",status:"Sehat",occupation:"",incomePerMonth:"",address:"",phone:"",medicalHistory:""})
const regions = ["Pati","Jepara","Ampel","Wonosobo","Sukabumi","Bandung"]
const money = (value:string) => value ? `Rp ${Number(value).toLocaleString("id-ID")}` : ""

export function RegisterForm() {
  const router=useRouter(); const [pending,startTransition]=useTransition(); const [step,setStep]=useState(1); const [error,setError]=useState("")
  const [data,setData]=useState({username:"",nik:"",fullName:"",dateOfBirth:"",gender:"",citaCita:"",wilayah:"",alamatLengkap:"",noHp:"",riwayatPenyakit:"",schoolName:"",gradeLevel:"",nilaiRataRata:"",jumlahSaudara:""})
  const [father,setFather]=useState(emptyFamily()); const [mother,setMother]=useState(emptyFamily()); const [guardian,setGuardian]=useState(emptyFamily())
  const [costs,setCosts]=useState<Cost[]>([{label:"SPP Bulanan",amount:""}]); const [files,setFiles]=useState({kk:"",rapor:"",foto:""})
  const set=(key:string,value:string)=>setData((d)=>({...d,[key]:value}))
  const next=()=>{setError(""); if(step===1&&!data.username.trim())return setError("Username wajib diisi."); if(step===2&&(!data.nik.match(/^\d{16}$/)||!data.fullName||!data.dateOfBirth||!data.gender||!data.wilayah))return setError("Lengkapi NIK 16 angka, profil, dan wilayah."); if(step===3&&(!data.schoolName||!data.gradeLevel))return setError("Lengkapi data pendidikan."); setStep((s)=>Math.min(6,s+1))}
  const submit=()=>{setError(""); const payload: RegisterPayload={...data,jumlahSaudara:Number(data.jumlahSaudara)||0,educationCosts:costs.map(c=>({label:c.label,amount:Number(c.amount)||0})),father,mother,guardian}; startTransition(async()=>{const result=await registerAction(payload); if(result.error)setError(result.error); else router.push("/daftar/sukses")})}
  return <div className="flex flex-1 flex-col gap-6 px-5 py-6"><div className="flex flex-col gap-2"><p className="font-bold text-primary">Langkah {step} dari 6</p><div className="flex gap-1.5" aria-hidden="true">{Array.from({length:6}).map((_,i)=><div key={i} className={`h-2 flex-1 rounded-full ${i<step?"bg-primary":"bg-secondary"}`}/>)}</div></div>{error&&<div role="alert" className="flex items-start gap-2 rounded-2xl bg-accent p-4 text-sm font-medium text-accent-foreground"><AlertCircle className="size-5 shrink-0" aria-hidden="true"/><span>{error}</span></div>}
  {step===1&&<Section title="Buat Akun" note="Username akan digunakan untuk masuk ke aplikasi."><Field label="Username"><Input value={data.username} onChange={e=>set("username",e.target.value)} placeholder="Contoh: budi2015" /></Field><Hint>Jangan gunakan spasi. Simpan username ini baik-baik.</Hint></Section>}
  {step===2&&<Section title="Profil Anak Asuh" note="Data identitas dan wilayah penempatan."><Field label="NIK (16 angka)"><Input inputMode="numeric" maxLength={16} value={data.nik} onChange={e=>set("nik",e.target.value.replace(/\D/g,""))} placeholder="Masukkan 16 angka NIK" /></Field><Field label="Nama Lengkap"><Input value={data.fullName} onChange={e=>set("fullName",e.target.value)} /></Field><Field label="Tanggal Lahir"><Input type="date" value={data.dateOfBirth} onChange={e=>set("dateOfBirth",e.target.value)} /></Field><Field label="Jenis Kelamin"><div className="grid grid-cols-2 gap-2">{["Laki-laki","Perempuan"].map(x=><Button key={x} type="button" variant={data.gender===x?"default":"outline"} onClick={()=>set("gender",x)}>{x}</Button>)}</div></Field><Field label="Wilayah"><select value={data.wilayah} onChange={e=>set("wilayah",e.target.value)} className="h-14 rounded-2xl border border-border bg-background px-4 text-foreground"><option value="">Pilih wilayah</option>{regions.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Cita-cita"><Input value={data.citaCita} onChange={e=>set("citaCita",e.target.value)} placeholder="Contoh: Dokter" /></Field><Field label="Alamat Lengkap"><Textarea value={data.alamatLengkap} onChange={e=>set("alamatLengkap",e.target.value)} /></Field><Field label="Nomor WhatsApp"><Input value={data.noHp} onChange={e=>set("noHp",e.target.value)} /></Field><Field label="Riwayat Penyakit"><Textarea value={data.riwayatPenyakit} onChange={e=>set("riwayatPenyakit",e.target.value)} placeholder="Isi - jika tidak ada" /></Field></Section>}
  {step===3&&<Section title="Pendidikan" note="Informasi sekolah dan kondisi pendidikan saat ini."><Field label="Nama Sekolah / Universitas"><Input value={data.schoolName} onChange={e=>set("schoolName",e.target.value)} /></Field><Field label="Kelas / Semester"><Input value={data.gradeLevel} onChange={e=>set("gradeLevel",e.target.value)} /></Field><Field label="Nilai Rata-rata / IPK"><Input value={data.nilaiRataRata} onChange={e=>set("nilaiRataRata",e.target.value)} /></Field><Field label="Jumlah Saudara"><Input type="number" min="0" value={data.jumlahSaudara} onChange={e=>set("jumlahSaudara",e.target.value)} /></Field><div className="flex flex-col gap-3"><Label className="font-bold">Rincian Biaya Pendidikan</Label>{costs.map((c,i)=><div key={i} className="flex gap-2"><Input placeholder="Jenis biaya" value={c.label} onChange={e=>setCosts(a=>a.map((x,j)=>j===i?{...x,label:e.target.value}:x))}/><Input className="w-32" inputMode="numeric" placeholder="Rp" value={c.amount} onChange={e=>setCosts(a=>a.map((x,j)=>j===i?{...x,amount:e.target.value.replace(/\D/g,"")}:x))}/>{costs.length>1&&<Button type="button" variant="ghost" size="icon" onClick={()=>setCosts(a=>a.filter((_,j)=>j!==i))} aria-label="Hapus biaya"><Trash2 aria-hidden="true"/></Button>}</div>)}<Button type="button" variant="outline" onClick={()=>setCosts(a=>[...a,{label:"",amount:""}])}><Plus data-icon="inline-start"/> Tambah biaya</Button></div></Section>}
  {step===4&&<Section title="Data Keluarga" note="Lengkapi data orang tua atau wali."><FamilyFields title="Data Ayah" value={father} onChange={setFather}/><FamilyFields title="Data Ibu" value={mother} onChange={setMother}/><FamilyFields title="Data Wali (opsional)" value={guardian} onChange={setGuardian}/></Section>}
  {step===5&&<Section title="Dokumen Pendukung" note="Format PDF, JPG, PNG, atau WebP. Maksimal 10 MB per file.">{([["kk","Kartu Keluarga"],["rapor","Rapor Terakhir"],["foto","Foto Anak"]] as const).map(([key,label])=><Field key={key} label={label}><Input type="file" accept="image/*,.pdf" onChange={e=>setFiles(f=>({...f,[key]:e.target.files?.[0]?.name||""}))}/>{files[key]&&<p className="text-sm text-muted-foreground">{files[key]}</p>}</Field>)}<Hint>Dokumen dapat dilengkapi kembali setelah akun dibuat.</Hint></Section>}
  {step===6&&<Section title="Periksa Pendaftaran" note="Pastikan data sudah benar sebelum dikirim."><div className="flex flex-col gap-2 rounded-2xl bg-secondary p-4 text-sm"><p><b>Nama:</b> {data.fullName||"-"}</p><p><b>NIK:</b> {data.nik||"-"}</p><p><b>Wilayah:</b> {data.wilayah||"-"}</p><p><b>Sekolah:</b> {data.schoolName||"-"}</p><p><b>Total biaya:</b> {money(String(costs.reduce((n,c)=>n+(Number(c.amount)||0),0)))||"-"}</p></div></Section>}
  <div className="flex flex-col gap-3">{step<6?<Button type="button" size="lg" onClick={next}>Lanjut <ArrowRight data-icon="inline-end"/></Button>:<Button type="button" size="lg" onClick={submit} disabled={pending}>{pending?"Menyimpan...":"Daftar Sekarang"} {!pending&&<Check data-icon="inline-end"/>}</Button>}{step>1?<Button type="button" size="lg" variant="secondary" onClick={()=>setStep(s=>s-1)}> <ArrowLeft data-icon="inline-start"/> Kembali</Button>:<Button size="lg" variant="ghost" nativeButton={false} render={<Link href="/">Batal</Link>}/>}</div></div>
}
function Section({title,note,children}:{title:string;note:string;children:React.ReactNode}){return <section className="flex flex-col gap-5"><div className="flex flex-col gap-1"><h2 className="text-xl font-extrabold text-foreground">{title}</h2><p className="text-sm leading-relaxed text-muted-foreground">{note}</p></div>{children}</section>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div className="flex flex-col gap-2"><Label className="font-bold text-foreground">{label}</Label>{children}</div>}
function Hint({children}:{children:React.ReactNode}){return <div className="flex items-start gap-2 rounded-2xl bg-secondary p-4 text-sm leading-relaxed text-secondary-foreground"><Info className="size-5 shrink-0" aria-hidden="true"/><span>{children}</span></div>}
function FamilyFields({title,value,onChange}:{title:string;value:Family;onChange:(v:Family)=>void}){const set=(p:Partial<Family>)=>onChange({...value,...p});return <div className="flex flex-col gap-4 rounded-2xl border border-border p-4"><h3 className="font-extrabold">{title}</h3><Field label="Nama"><Input value={value.name} onChange={e=>set({name:e.target.value})}/></Field><Field label="Status"><select value={value.status} onChange={e=>set({status:e.target.value})} className="h-12 rounded-xl border border-border bg-background px-3"><option>Sehat</option><option>Sakit</option><option>Meninggal Dunia</option></select></Field><Field label="Pekerjaan"><Input value={value.occupation} onChange={e=>set({occupation:e.target.value})}/></Field><Field label="Penghasilan per bulan"><Input value={value.incomePerMonth} onChange={e=>set({incomePerMonth:e.target.value})}/></Field><Field label="Alamat"><Textarea value={value.address} onChange={e=>set({address:e.target.value})}/></Field><Field label="Nomor telepon"><Input value={value.phone} onChange={e=>set({phone:e.target.value})}/></Field><Field label="Riwayat penyakit"><Textarea value={value.medicalHistory} onChange={e=>set({medicalHistory:e.target.value})}/></Field></div>}
